### PR TITLE
SLHC Memory Fix ->>> swap out caches for PFEGAlgo & HGCClusterizer

### PR DESCRIPTION
**Pull request by lgray**

### CODE REVIEW

**Comment by lgray** [comment]
@mark-grimes for https://github.com/cms-sw/cmssw/pull/9203 : please go ahead and merge into your PR.

**Comment by mark-grimes** [comment]
I'll start a job to check the results and put this in when I have the plots to go with it.  I'll open a new PR using your branch though to keep the issues separate, I'm starting to get confused which plot refers to what.
I'd been ignoring PFEGammaProducer - I thought because the big jump came in beginRun it was something unavoidable like a geom service or something.  We'll see how it changes once I've tested.

Thanks.

**Comment by lgray** [comment]
It looks like it's in BeginRun, but there are kept lists of PFCandidates
between events.
The MVAs may also be the next biggest user, but in that case I'm surprised
they don't show up in PFAlgo.

Hope these changes help!

-Lindsey

**Comment by mark-grimes** [comment]
Saves ~50 Mb.  How do you mean show up in PFAlgo?  I can only break down by EDProducer instance so it will show up in whichever producer uses it.

Put in a PR directly #9227 so closing this.

**Pull request closed without merging**
